### ISSUE TITLE
[JsonSerializer] IsEquivalentTo

### ISSUE THREAD

**Issue by pavel-b-novikov** [nor7easter/nsudotnet#2]
Кто научил вас использовать этот метод и для чего он используется вне тестовых заданий?

**Comment by pavel-b-novikov** [comment]
Вдогонку: 
```Type.GetType("System.String")```
Ну вы конено нашли оптимальный способ достать тип строки, ага...

**Comment by nor7easter** [comment]
На isEquivalentTo наткнулась случайно, затрудняюсь ответить, кому и для чего он нужен. Я всё вышеперечисленное исправила на следующее:
`elementType == typeof(string)`

**Comment by pavel-b-novikov** [comment]
А я-то думал мы окунемся с вами в дивный мир COM+ и Type GUID-ов.. Эх. не судьба :)
