### ISSUE TITLE
[JsonSerializer] fieldType.IsArray

### ISSUE THREAD

**Issue by pavel-b-novikov** [nor7easter/nsudotnet#3]
А как быть с остальными коллекциями?

Сделайте вот что. Подите в исходники RT (https://github.com/reinforced/Reinforced.Typings) и возьмите оттуда нормальную проверку на коллекцию. Тогда я не буду смотреть код дальше.

**Comment by nor7easter** [comment]
Добавила коллекции

**Comment by pavel-b-novikov** [comment]
Круто!
